<script type="text/javascript" src="http://player.youku.com/jsapi"></script>
<div id="youkuplayer" style="width:280px;height:200px"></div>
<script type="text/javascript">
player = new YKU.Player('youkuplayer',{
styleid: '0',
autoplay: '0',
show_related:'0',
client_id: 'e1a4f3a23c0bed2a',
vid: 'XMTQzNzI4NDUwOA=='
});
</script>

<div id="youkuplayer1" style="width:280px;height:200px"></div>
<script type="text/javascript">
player = new YKU.Player('youkuplayer1',{
styleid: '0',
autoplay: '0',
show_related:'0',
client_id: 'e1a4f3a23c0bed2a',
vid: 'XMTQzNzI4NDUwOA=='
});
</script>

<div id="youkuplayer2" style="width:280px;height:200px"></div>
<script type="text/javascript">
player = new YKU.Player('youkuplayer2',{
styleid: '0',
autoplay: '0',
show_related:'0',
client_id: 'e1a4f3a23c0bed2a',
vid: 'XMTQzNzI4NDUwOA=='
});
</script>