<li class="active"><a href="<?php echo $this->url('/study/')?>" onclick="return false;">Overview</a></li>
<li>
    <a href="###" class="PROGRAM-product_menu_fold" onclick="return false;" data-flag="plus"><span class="glyphicon glyphicon-plus interval-r-5"></span>后端技术</a>
    <ul class="nav nav-sub-sidebar hide">
        <li>
            <a href="###" class="PROGRAM-product_menu_fold" onclick="return false;" data-flag="plus"><span class="glyphicon glyphicon-plus interval-r-5"></span>操作系统</a>
            <ul class="nav nav-sub-sidebar hide">
                <li><a href="#">Linux</a></li>
            </ul>
        </li>
        <li>
            <a href="###" class="PROGRAM-product_menu_fold" onclick="return false;" data-flag="plus"><span class="glyphicon glyphicon-plus interval-r-5"></span>Web服务器</a>
            <ul class="nav nav-sub-sidebar hide">
                <li><a href="#">Nginx</a></li>
            </ul>
        </li>
        <li>
            <a href="###" class="PROGRAM-product_menu_fold" onclick="return false;" data-flag="plus"><span class="glyphicon glyphicon-plus interval-r-5"></span>数据库</a>
            <ul class="nav nav-sub-sidebar hide">
                <li><a href="#">Mysql</a></li>
            </ul>
        </li>
        <li>
            <a href="###" class="PROGRAM-product_menu_fold" onclick="return false;" data-flag="plus"><span class="glyphicon glyphicon-plus interval-r-5"></span>缓存数据库</a>
            <ul class="nav nav-sub-sidebar hide">
                <li><a href="#">Redis</a></li>
                <li><a href="#">Memcache</a></li>
            </ul>
        </li>
        <li>
            <a href="###" class="PROGRAM-product_menu_fold" onclick="return false;" data-flag="plus"><span class="glyphicon glyphicon-plus interval-r-5"></span>语言</a>
            <ul class="nav nav-sub-sidebar hide">
                <li><a href="#">PHP</a></li>
                <li><a href="#">Lua</a></li>
                <li><a href="#">Shell</a></li>
            </ul>
        </li>
    </ul>
</li>
<li>
    <a href="###" class="PROGRAM-product_menu_fold" onclick="return false;" data-flag="plus"><span class="glyphicon glyphicon-plus interval-r-5"></span>前端技术</a>
    <ul class="nav nav-sub-sidebar hide">
        <li><a href="#">Javasctipt 脚本语言</a></li>
        <li>
            <a href="###" class="PROGRAM-product_menu_fold" onclick="return false;" data-flag="plus"><span class="glyphicon glyphicon-plus interval-r-5"></span>Css 样式表</a>
            <ul class="nav nav-sub-sidebar hide">
                <li><a href="#">Css1</a></li>
                <li><a href="#">Css2</a></li>
                <li><a href="#">Css3</a></li>
            </ul>
        </li>
        <li>
            <a href="###" class="PROGRAM-product_menu_fold" onclick="return false;" data-flag="plus"><span class="glyphicon glyphicon-plus interval-r-5"></span>Html 超文本标记语言</a>
            <ul class="nav nav-sub-sidebar hide">
                <li><a href="#">html4</a></li>
                <li><a href="#">html5</a></li>
            </ul>
        </li>
    </ul>
</li>