<li class="active"><a href="###" onclick="return false;">Overview</a><span style="position: absolute;top: 3px;right:5px;"><a href="###" class="btn btn-default" onclick="return false;">创建产品</a></span></li>
<li>
    <a href="###" class="PROGRAM-product_menu_fold" onclick="return false;" data-flag="plus"><span class="glyphicon glyphicon-plus interval-r-5"></span>网站 - 产品列表</a>
    <ul class="nav nav-sub-sidebar hide">
        <li><a href="#">优谈网</a></li>
        <li><a href="#">优谈宝宝</a></li>
    </ul>
</li>
<li>
    <a href="###" class="PROGRAM-product_menu_fold" onclick="return false;" data-flag="plus"><span class="glyphicon glyphicon-plus interval-r-5"></span>APP - 产品列表</a>
    <ul class="nav nav-sub-sidebar hide">
        <li><a href="#">优谈宝宝</a></li>
        <li><a href="#">大姨妈</a></li>
    </ul>
</li>