<li class="active"><a href="<?php echo $this->url('/frameworkStudy/')?>" onclick="return false;">Overview</a></li>
<li>
    <a href="###" class="PROGRAM-product_menu_fold" onclick="return false;" data-flag="plus"><span class="glyphicon glyphicon-plus interval-r-5"></span>框架介绍</a>
    <ul class="nav nav-sub-sidebar hide">
        <li><a href="<?php echo $this->url('/frameworkStudy/designIdea')?>">框架设计思想</a></li>
        <li><a href="<?php echo $this->url('/frameworkStudy/directoryStructure')?>">框架目录结构</a></li>
    </ul>
</li>
<li>
    <a href="###" class="PROGRAM-product_menu_fold" onclick="return false;" data-flag="plus"><span class="glyphicon glyphicon-plus interval-r-5"></span>框架类库使用 - 核心类库</a>
    <ul class="nav nav-sub-sidebar hide">
        <li><a href="#">F_Application</a></li>
        <li><a href="#">F_Exception</a></li>
        <li><a href="#">F_Exception</a></li>
    </ul>
</li>
<li>
    <a href="###" class="PROGRAM-product_menu_fold" onclick="return false;" data-flag="plus"><span class="glyphicon glyphicon-plus interval-r-5"></span>框架类库使用 - 工具类库</a>
    <ul class="nav nav-sub-sidebar hide">
        <li><a href="#">核心类库</a></li>
        <li><a href="#">工具类库</a></li>
    </ul>
</li>