<!doctype html> 
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?php echo $this->headTitle('F')?></title>
        <?php echo $this->headMeta('F', 'keywords')->headMeta('F', 'description')?>
        <?php $this->headLink()->prependStylesheet('/asset/css/??modules/bootstrap/bootstrap.min.css,modules/bootstrap/bootstrap-theme.min.css,modules/framework/pieces.css')?>
        <?php echo $this->headLink()?>
        <?php echo $this->initPageNecessary()?>
        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
        <!--[if lt IE 9]><script src="/asset/js/modules/bootstrap/ie8-responsive-file-warning.js"></script><![endif]-->
        <script src="/asset/js/modules/bootstrap/ie-emulation-modes-warning.js"></script>
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="/asset/js/modules/bootstrap/html5shiv.js"></script>
          <script src="/asset/js/modules/bootstrap/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-11 col-md-12 main">
                    <?php echo $scriptContent ?>
                </div>
            </div>
        </div>
        <?php
        echo $this->script()->outputScript('/asset/js/??modules/lab/2.0.3/lab.js,modules/jquery/1.11.1/jquery.min.js,modules/bootstrap/bootstrap.min.js,modules/bootstrap/ie10-viewport-bug-workaround.js')->lastWait(function() {
            //页面中所有JS加载完毕后才开始执行的
            return '__wait(false, true);';
        });
        ?>
    </body>
</html>