<!doctype html> 
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?php echo $this->headTitle('F')?></title>
        <?php echo $this->headMeta('F', 'keywords')->headMeta('F', 'description')?>
        <?php $this->headLink()->prependStylesheet('/asset/css/??modules/bootstrap/bootstrap.min.css,modules/bootstrap/bootstrap-theme.min.css,modules/framework/framework.css')?>
        <?php echo $this->headLink()?>
        <?php echo $this->initPageNecessary()?>
        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
        <!--[if lt IE 9]><script src="/asset/js/modules/bootstrap/ie8-responsive-file-warning.js"></script><![endif]-->
        <script src="/asset/js/modules/bootstrap/ie-emulation-modes-warning.js"></script>
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="/asset/js/modules/bootstrap/html5shiv.js"></script>
          <script src="/asset/js/modules/bootstrap/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">SOP</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">Dashboard</a></li>
                        <li><a href="#">Settings</a></li>
                        <li><a href="#">Profile</a></li>
                        <li><a href="#">Help</a></li>
                    </ul>
                    <form class="navbar-form navbar-right">
                        <input type="text" class="form-control" placeholder="Search...">
                    </form>
                </div>
            </div>
        </nav>
        <div class="container-fluid">
            <div class="row">
                <div id="sop-sidebarBoxId" class="col-sm-3 col-md-2 sidebar">
                    <ul class="nav nav-sidebar">
                        <?php if($this->visitCheck(array('module' => 'product'))):?>
                            <?php echo $this->render('slot/menu_list_of_product')?>
                        <?php else:?>
                        <li class="active"><a href="###" onclick="return false;">Overview</a></li>
                        <?php endif?>
                    </ul>
                    <script>
                        __wait(function(){
                            //菜单折叠操作
                            $('.PROGRAM-product_menu_fold').on('click', function(){
                                var $this = $(this);
                                var flag = $this.data('flag');
                                if (flag === 'plus') {
                                    $('span', this).removeClass('glyphicon-plus').addClass('glyphicon-minus');
                                    $('ul', $this.parent()).removeClass('hide');
                                    $this.data('flag', 'minus');
                                } else {
                                    $('span', this).removeClass('glyphicon-minus').addClass('glyphicon-plus');
                                    $('ul', $this.parent()).addClass('hide');
                                    $this.data('flag', 'plus');
                                }
                            });
                        });
                    </script>
                    <!--ul class="nav nav-sidebar">
                        <li><a href="">Nav item</a></li>
                        <li><a href="">Nav item again</a></li>
                        <li><a href="">One more nav</a></li>
                        <li><a href="">Another nav item</a></li>
                        <li><a href="">More navigation</a></li>
                    </ul>
                    <ul class="nav nav-sidebar">
                        <li><a href="">Nav item again</a></li>
                        <li><a href="">One more nav</a></li>
                        <li><a href="">Another nav item</a></li>
                    </ul-->
                </div>
                <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                    <?php echo $scriptContent ?>
                </div>
            </div>
        </div>
        <?php
        echo $this->script()->outputScript('/asset/js/??modules/lab/2.0.3/lab.js,modules/jquery/1.11.1/jquery.min.js,modules/bootstrap/bootstrap.min.js,modules/bootstrap/ie10-viewport-bug-workaround.js')->lastWait(function() {
            //页面中所有JS加载完毕后才开始执行的
            return '__wait(false, true);';
        });
        ?>
    </body>
</html>